### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by BoredinBerlin** [limitedeternity/VK-Audio-Downloader#1]
Hello -- Installed and managed to run your downloader, but it doesn't appear to be working. Has VK changed something?

> vk-audio-downloader@1.0.0 start /Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master
> node index.js

(node:19611) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Promise (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:10:32)
    at new Promise (<anonymous>)
    at download (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:9:12)
    at Page.interceptorCallback (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:112:19)
    at Page.emit (events.js:182:13)
    at NetworkManager.Page._networkManager.on.event (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/node_modules/puppeteer/lib/Page.js:122:74)
    at NetworkManager.emit (events.js:182:13)
    at NetworkManager._handleRequestStart (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/node_modules/puppeteer/lib/NetworkManager.js:221:10)
(node:19611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19611) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19611) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Promise (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:10:32)
    at new Promise (<anonymous>)
    at download (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:9:12)
    at Page.interceptorCallback (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:112:19)
    at Page.emit (events.js:182:13)
    at NetworkManager.Page._networkManager.on.event (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/node_modules/puppeteer/lib/Page.js:122:74)
    at NetworkManager.emit (events.js:182:13)
    at NetworkManager._handleRequestStart (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/node_modules/puppeteer/lib/NetworkManager.js:221:10)
(node:19611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:19611) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Promise (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:10:32)
    at new Promise (<anonymous>)
    at download (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:9:12)
    at Page.interceptorCallback (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:112:19)
    at Page.emit (events.js:182:13)
    at NetworkManager.Page._networkManager.on.event (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/node_modules/puppeteer/lib/Page.js:122:74)
    at NetworkManager.emit (events.js:182:13)
    at NetworkManager._handleRequestStart (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/node_modules/puppeteer/lib/NetworkManager.js:221:10)
(node:19611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:19611) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Promise (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:10:32)
    at new Promise (<anonymous>)
    at download (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:9:12)
    at Page.interceptorCallback (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:112:19)
    at Page.emit (events.js:182:13)
    at NetworkManager.Page._networkManager.on.event (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/node_modules/puppeteer/lib/Page.js:122:74)
    at NetworkManager.emit (events.js:182:13)
    at NetworkManager._handleRequestStart (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/node_modules/puppeteer/lib/NetworkManager.js:221:10)
(node:19611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:19611) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Promise (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:10:32)
    at new Promise (<anonymous>)
    at download (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:9:12)
    at Page.interceptorCallback (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:112:19)
    at Page.emit (events.js:182:13)
    at NetworkManager.Page._networkManager.on.event (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/node_modules/puppeteer/lib/Page.js:122:74)
    at NetworkManager.emit (events.js:182:13)
    at NetworkManager._handleRequestStart (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/node_modules/puppeteer/lib/NetworkManager.js:221:10)
(node:19611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:19611) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Promise (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:10:32)
    at new Promise (<anonymous>)
    at download (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:9:12)
    at Page.interceptorCallback (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/index.js:112:19)
    at Page.emit (events.js:182:13)
    at NetworkManager.Page._networkManager.on.event (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/node_modules/puppeteer/lib/Page.js:122:74)
    at NetworkManager.emit (events.js:182:13)
    at NetworkManager._handleRequestStart (/Users/Xxxxxx/Downloads/VK-Audio-Downloader-master/VK-Audio-Downloader-master/node_modules/puppeteer/lib/NetworkManager.js:221:10)
(node:19611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)

**Comment by limitedeternity** [comment]
Hi, @BoredinBerlin.
Everything works as expected, have just checked it.
After script starts, browser window should show up. After that, you login into your VK account and navigate to an audio page (community one or your own). Page will automatically scroll to bottom and then download will start. You can stop process whenever you want - just terminate program by using Ctrl + C in console window.
Good luck!
